CREATE TABLE IF NOT EXISTS `sessions` (
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL,
    `user_id` INT NOT NULL,
    `iat` BIGINT UNSIGNED NOT NULL,
    `exp` BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;